  GNU nano 6.2                                       docker-compose.yml                                                 services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211 # Optional but recommended
         - PLAYERS=16 # Optional but recommended
         - SERVER_PASSWORD="SomePassword" # Optional but recommended
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - RCON_PORT=25575
         - TZ=UTC
         - ADMIN_PASSWORD="SomePassword"
         - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SER>         
         - SERVER_NAME="SomeName"
      volumes:
         - ./palworld:/palworld/